name: CI CD for API
on:
  push:
    branches:
      - Main
    paths:
      - Backend/**

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code ✔️
        uses: actions/checkout@v2

      - name: Setup .NET 5
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '5.0.x'

      - name: Restore Dependencies
        run: dotnet restore Backend

      - name: Build App
        run: dotnet build -c Release --no-restore Backend